export const CHANGE_PLACE_LINK_INPUT_ACTION = 'FORMS/CHANGE_PLACE_LINK_INPUT_ACTION';
export const CHANGE_PLACE_NAME_INPUT_ACTION = 'FORMS/CHANGE_PLACE_NAME_INPUT_ACTION';
export const CHANGE_USER_NAME_INPUT_ACTION = 'FORMS/CHANGE_USER_NAME_INPUT_ACTION';
export const CHANGE_USER_JOB_INPUT_ACTION = 'FORMS/CHANGE_USER_JOB_INPUT_ACTION';
export const FETCH_DATA_ACTION = 'CARD/FETCH_DATA_ACTION';
export const LOAD_DATA_ACTION = 'CARD/LOAD_DATA_ACTION';