export const CHANGE_LINK_INPUT_ACTION = 'CHANGE_LINK_INPUT_ACTION';
export const CHANGE_NAME_INPUT_ACTION = 'CHANGE_NAME_INPUT_ACTION';
export const PLACES_FETCH_DATA_ACTION = 'PLACES_FETCH_DATA_ACTION';
export const PLACES_LOAD_DATA_ACTION = 'PLACES_LOAD_DATA_ACTION';
