export const CHANGE_LINK_INPUT_ACTION = 'FORM/CHANGE_LINK_INPUT_ACTION';
export const CHANGE_NAME_INPUT_ACTION = 'FORM/CHANGE_NAME_INPUT_ACTION';
export const FETCH_DATA_ACTION = 'CARD/FETCH_DATA_ACTION';
export const LOAD_DATA_ACTION = 'CARD/LOAD_DATA_ACTION';
